version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: local_db
    restart: unless-stopped
